@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

###
GET {{host}}/api/persons

###
GET {{host}}/api/persons/66598438029ad7a41897f5ab

###
POST {{host}}/api/persons 
Content-Type: application/json

{
    "name": "Joe Dane",
    "number": "012-345-6789"
}

###
DELETE  {{host}}/api/persons/665d9188aa89decbcaa1c562

