@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

###
GET {{host}}/api/persons

###
GET {{host}}/api/persons/1

###
POST {{host}}/api/persons 
Content-Type: application/json

{
    "name": "Jane Doe",
    "number": "012-345-6789"
}

###
DELETE  {{host}}/api/persons/622

